query ListQuery {
  ddArticles {
    _id
    title
    description
    content
    link
    date
    thumbnail
    isTop
    type
  }
}
query GetDdArticle($artId: String!) {
  getDdArticle(artId: $artId) {
    title
    thumbnail
    description
    date
    link
    content
    type
    isTop
  }
}
mutation RemoveDdArticle($artId: String!) {
  removeDdArticle(artId: $artId) {
    title
    thumbnail
  }
}
mutation UpdateDdArticle(
  $id: String!
  $title: String
  $description: String
  $content: String
  $link: String
  $date: String
  $thumbnail: String
  $isTop: Boolean
  $type: Int
) {
  updateDdArticle(
    dDArticleInput: {
      id: $id
      title: $title
      description: $description
      content: $content
      link: $link
      date: $date
      thumbnail: $thumbnail
      isTop: $isTop
      type: $type
    }
  ) {
    title
    thumbnail
  }
}
mutation InsertDdArticle(
  $title: String!
  $description: String!
  $content: String!
  $link: String!
  $date: String!
  $thumbnail: String!
) {
  createDdArticle(
    dDArticleInput: {
      title: $title
      description: $description
      content: $content
      link: $link
      date: $date
      thumbnail: $thumbnail
    }
  ) {
    title
    thumbnail
  }
}
